"""
Newsletter builder — assembles summarized deals into a structured document.

Groups deals by type, generates an executive summary, and renders
both markdown (for the Streamlit app) and .docx (for the Word deliverable).
"""

import logging
from collections import defaultdict
from datetime import datetime, timezone

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

logger = logging.getLogger(__name__)

# Friendly section names for deal types
DEAL_TYPE_LABELS = {
    "acquisition": "Acquisitions",
    "merger": "Mergers",
    "stake_sale": "Stake Sales",
    "funding": "Funding Rounds",
    "divestment": "Divestments",
    "ipo": "IPO Activity",
    "jv": "Joint Ventures & Partnerships",
    "other": "Other Deals",
}


def _group_by_deal_type(articles: list[dict]) -> dict[str, list[dict]]:
    """Group kept articles by their deal_type, sorted by credibility."""
    groups = defaultdict(list)
    for article in articles:
        if article.get("pipeline_status") != "kept":
            continue
        deal_type = article.get("deal_type", "other")
        groups[deal_type].append(article)

    # Sort each group by credibility tier (ascending = best first)
    for deal_type in groups:
        groups[deal_type].sort(key=lambda a: a.get("credibility_tier", 3))

    return dict(groups)


def _generate_executive_summary(groups: dict[str, list[dict]]) -> str:
    """
    Generate a 2-3 line executive summary from the grouped deals.
    Rule-based template — quick and deterministic.
    """
    total_deals = sum(len(deals) for deals in groups.values())

    if total_deals == 0:
        return "No significant FMCG deals were identified in the current reporting period."

    # Find the most notable deal (highest credibility, first in sort)
    all_kept = []
    for deals in groups.values():
        all_kept.extend(deals)

    notable = all_kept[0] if all_kept else None
    notable_str = ""
    if notable:
        companies = notable.get("companies_involved", [])
        if companies:
            notable_str = f", led by activity involving {companies[0]}"
        else:
            notable_str = f", including: {notable.get('title', '')[:80]}"

    deal_types_mentioned = [
        DEAL_TYPE_LABELS.get(dt, dt) for dt in groups.keys()
    ]
    types_str = ", ".join(deal_types_mentioned[:3])

    summary = (
        f"This period saw {total_deals} identified FMCG deal(s) spanning "
        f"{types_str}{notable_str}. "
        f"The following sections break down each transaction by category."
    )
    return summary


def build_markdown_newsletter(articles: list[dict]) -> str:
    """
    Build the newsletter as markdown text for rendering in Streamlit.
    """
    groups = _group_by_deal_type(articles)
    exec_summary = _generate_executive_summary(groups)
    now = datetime.now(timezone.utc).strftime("%B %d, %Y")

    lines = [
        "# FMCG Industry Intelligence — M&A Newsletter",
        f"**Report Date:** {now}",
        "",
        "## Executive Summary",
        exec_summary,
        "",
        "---",
        "",
    ]

    if not groups:
        lines.append("*No deals matched the current filter criteria.*")
        return "\n".join(lines)

    for deal_type, deals in groups.items():
        section_label = DEAL_TYPE_LABELS.get(deal_type, deal_type.title())
        lines.append(f"## {section_label}")
        lines.append("")

        for deal in deals:
            title = deal.get("title", "Untitled")
            companies = ", ".join(deal.get("companies_involved", [])) or "—"
            value = deal.get("deal_value", "undisclosed")
            summary = deal.get("summary", "No summary available.")
            source = deal.get("source_domain", "unknown")
            tier = deal.get("credibility_tier", 3)
            tier_label = {1: "★★★", 2: "★★☆", 3: "★☆☆"}.get(tier, "★☆☆")
            url = deal.get("url", "#")

            lines.append(f"### {title}")
            lines.append(f"**Companies:** {companies} | **Value:** {value}")
            lines.append(f"**Source:** [{source}]({url}) ({tier_label})")
            lines.append("")
            lines.append(summary)
            lines.append("")
            lines.append("---")
            lines.append("")

    lines.append("*Generated by FMCG M&A Newsletter Agent*")
    return "\n".join(lines)


def build_docx_newsletter(articles: list[dict], output_path: str) -> str:
    """
    Build the newsletter as a Word document (.docx).

    Returns the path to the saved file.
    """
    groups = _group_by_deal_type(articles)
    exec_summary = _generate_executive_summary(groups)
    now = datetime.now(timezone.utc).strftime("%B %d, %Y")

    doc = Document()

    # -- Title --
    title_para = doc.add_heading("FMCG Industry Intelligence", level=0)
    subtitle = doc.add_heading("M&A & Investment Activity Newsletter", level=1)

    # Date
    date_para = doc.add_paragraph()
    date_run = date_para.add_run(f"Report Date: {now}")
    date_run.font.size = Pt(11)
    date_run.font.color.rgb = RGBColor(100, 100, 100)

    # Executive summary
    doc.add_heading("Executive Summary", level=2)
    exec_para = doc.add_paragraph(exec_summary)
    exec_para.style.font.size = Pt(11)

    doc.add_paragraph("—" * 50)

    if not groups:
        doc.add_paragraph("No deals matched the current filter criteria.")
    else:
        for deal_type, deals in groups.items():
            section_label = DEAL_TYPE_LABELS.get(deal_type, deal_type.title())
            doc.add_heading(section_label, level=2)

            for deal in deals:
                title = deal.get("title", "Untitled")
                companies = ", ".join(deal.get("companies_involved", [])) or "—"
                value = deal.get("deal_value", "undisclosed")
                summary = deal.get("summary", "No summary available.")
                source = deal.get("source_domain", "unknown")
                tier = deal.get("credibility_tier", 3)
                url = deal.get("url", "")

                # Deal title
                deal_heading = doc.add_heading(title, level=3)

                # Metadata line
                meta_para = doc.add_paragraph()
                meta_para.add_run("Companies: ").bold = True
                meta_para.add_run(f"{companies}  |  ")
                meta_para.add_run("Value: ").bold = True
                meta_para.add_run(f"{value}  |  ")
                meta_para.add_run("Source: ").bold = True
                meta_para.add_run(f"{source} (Tier {tier})")

                # Summary
                doc.add_paragraph(summary)

                # Source link
                if url:
                    link_para = doc.add_paragraph()
                    link_run = link_para.add_run(f"Read more: {url}")
                    link_run.font.size = Pt(9)
                    link_run.font.color.rgb = RGBColor(0, 102, 204)

                doc.add_paragraph("")  # spacer

    # Footer
    doc.add_paragraph("—" * 50)
    footer = doc.add_paragraph()
    footer_run = footer.add_run("Generated by FMCG M&A Newsletter Agent")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)

    doc.save(output_path)
    logger.info("Newsletter saved to %s", output_path)
    return output_path
